// ==========================================
// Edorapad API Endpoints Matrix
// ==========================================

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/auth/login',
    REGISTER: '/api/auth/signup',
    LOGOUT: '/api/auth/logout',
    REFRESH: '/api/auth/refresh',
    FORGOT_PASSWORD: '/api/auth/forgot-password',
    RESET_PASSWORD: '/api/auth/reset-password',
    GOOGLE: '/api/auth/google',
    VERIFY_PHONE: '/api/auth/verify-phone',
    RESEND_OTP: '/api/auth/resend-otp',
    VERIFY_PHONE_SECURE: '/api/auth/verify-phone-secure',
    RESEND_OTP_SECURE: '/api/auth/resend-otp-secure',
    VERIFY_FACE: '/api/auth/face-verify',
    FACE_INIT: '/api/auth/face-init',
    FACE_CHALLENGE: '/api/auth/face-challenge',
    REGISTER_DEVICE: '/api/push/device-token'
  },
  PUSH: {
    DEVICE_TOKEN: '/api/push/device-token'
  },
  INSTITUTE: {
    STATS: '/api/institute/dashboard/stats',
    STAFF_DISTRIBUTION: '/api/institute/dashboard/staff-distribution',
    ADMISSION_REQUESTS: '/api/institute/admission/requests',
    ADMISSION_REQUEST_BY_ID: (id: string) => `/api/institute/admission/requests/${id}`,
    UPDATE_ADMISSION_STATUS: (id: string) => `/api/institute/admission/requests/${id}/status`,
    VIEW_DOCUMENT: '/api/institute/admission/requests/view-document',
    COURSES: '/api/institute/course/all',
    DEPARTMENTS: '/api/institute/department/all',
    STAFF_ALL: '/api/institute/staff/all',
    NOTIFICATIONS: '/api/institute/notification/all',
    NOTIFICATIONS_ALT: '/api/institute/notifications',
    MARK_NOTIFICATION_READ: (id: string) => `/api/institute/notification/${id}`,
    MARK_ALL_NOTIFICATIONS_READ: '/api/institute/notification/mark-all-read',
    LEAVES: '/api/institute/staff/leave/all',
    UPDATE_LEAVE_STATUS: (id: string) => `/api/institute/staff/leave/${id}/status`,
    APPROVE_LEAVE: (id: string) => `/api/institute/staff/leave/${id}/status`,
    REJECT_LEAVE: (id: string) => `/api/institute/staff/leave/${id}/status`,
    BATCHES: '/api/institute/batch/all',
    CREATE_BATCH: '/api/institute/batch/create',
    BATCH_BY_ID: (id: string) => `/api/institute/batch/${id}`,
    UPDATE_BATCH: (id: string) => `/api/institute/batch/${id}`,
    DELETE_BATCH: (id: string) => `/api/institute/batch/${id}`,
    STUDENTS_ALL: '/api/institute/students/all',
    CERTIFICATES: '/api/institute/certificate/all',
    FINANCIAL_OVERVIEW: '/api/institute/dashboard/financial-overview',
    DEPARTMENT_BREAKDOWN: '/api/institute/dashboard/department-breakdown',
    COMMUNITIES: '/api/institute/communities',
    COMMUNITY_BY_ID: (id: string) => `/api/institute/communities/${id}`,
    COMMUNITY_MEMBERS: (id: string) => `/api/institute/communities/${id}/members`,
    COMMUNITY_MEMBER_BY_ID: (communityId: string, userId: string) => `/api/institute/communities/${communityId}/members/${userId}`,
    COMMUNITY_MESSAGES: (id: string) => `/api/institute/communities/${id}/messages`,
    SEND_COMMUNITY_MESSAGE: (id: string) => `/api/institute/communities/${id}/messages`,
    SETTINGS: '/api/institute/settings',
    UPDATE_SETTINGS: '/api/institute/settings',
    UPDATE_SETTINGS_BASIC: '/api/institute/settings/basic',
    UPDATE_SETTINGS_BANK: '/api/institute/settings/bank',
    UPDATE_SETTINGS_ALERTS: '/api/institute/settings/alerts',
    STRIPE_STATUS: '/api/institute/finance/stripe/status',
    STRIPE_ONBOARD: '/api/institute/finance/stripe/onboard',
  },
  CERTIFICATE_MANAGEMENT: {
    STATS: '/api/certificates/stats',
    REQUESTS: (status?: string | null) => status ? `/api/certificates/requests?status=${status}` : '/api/certificates/requests',
    APPROVE_REQUEST: (id: string) => `/api/certificates/requests/${id}/approve`,
    BULK_APPROVE: '/api/certificates/requests/bulk-approve',
    TEMPLATES: (status?: string | null) => status ? `/api/certificates/templates?status=${status}` : '/api/certificates/templates',
    TEMPLATE_BY_ID: (id: string) => `/api/certificates/templates/${id}`,
    CREATE_TEMPLATE: '/api/certificates/templates',
    UPDATE_TEMPLATE: (id: string) => `/api/certificates/templates/${id}`,
    DELETE_TEMPLATE: (id: string) => `/api/certificates/templates/${id}`,
    ALL_CERTIFICATES: (query?: string) => query ? `/api/certificates?${query}` : '/api/certificates',
    GENERATE: '/api/certificates/generate',
    UPLOAD: '/api/certificates/upload',
    CERTIFICATE_BY_ID: (id: string) => `/api/certificates/${id}`,
    UPDATE_CERTIFICATE_URL: (id: string) => `/api/certificates/${id}/url`,
    SEARCH_STUDENTS: (query: string) => `/api/certificates/search/students?${query}`
  },
  ATTENDANCE: {
    DAILY_WORKSHEET: (date: string) => `/api/institute/attendance/daily-worksheet?date=${date}`,
    MARK_STAFF: '/api/institute/attendance/mark',
    BULK_MARK_STAFF: '/api/institute/attendance/bulk-mark',
    ALL_STAFF_MONTHLY: (month: string | number, year: string | number) => 
      `/api/institute/attendance/all-staff-monthly?month=${month}&year=${year}`,
    MARK_STUDENT: '/api/institute/student-attendance/mark',
    BULK_MARK_STUDENT: '/api/institute/student-attendance/bulk-mark',
    BATCH_MONTHLY: (batchId: string, month: number, year: number) => 
      `/api/institute/student-attendance/batch/${batchId}/monthly?month=${month}&year=${year}`,
    BATCH_DAILY: (batchId: string, date: string) => 
      `/api/institute/student-attendance/batch/${batchId}?date=${date}`
  },
  TUTOR: {
    DASHBOARD: '/api/tutor/dashboard',
    STATS: '/api/institute/tutor/dashboard/stats',
    DASHBOARD_TASKS: '/api/institute/tutor/dashboard/tasks',
    DASHBOARD_ATTENDANCE: '/api/institute/tutor/dashboard/attendance',
    DASHBOARD_BATCH_ATTENDANCE: '/api/institute/tutor/dashboard/batch-attendance',
    DASHBOARD_UPCOMING_ACTIVITIES: '/api/institute/tutor/dashboard/upcoming-activities',
    MONTHLY_ATTENDANCE: (month: string | number, year: string | number) =>
      `/api/institute/attendance/my-monthly-report?month=${month}&year=${year}`,
    BATCHES: '/api/institute/batch/tutor-batches',
    LIVE_CLASSES: '/api/tutor/live-classes',
    SCHEDULE_LIVE_CLASS: '/api/tutor/live-classes/schedule',
    ASSESSMENTS: '/api/tutor/assessments',
    TASKS: '/api/institute/tasks',
    TASK_BY_ID: (id: string) => `/api/institute/tasks/${id}`,
    LEAVE_REQUEST: '/api/institute/staff/leave/apply',
    LEAVE_HISTORY: '/api/institute/staff/leave/my-leaves',
    PROFILE: '/api/institute/tutor/settings',
    SETTINGS: '/api/institute/tutor/settings',
    UPDATE_SETTINGS_PROFILE: '/api/institute/tutor/settings/profile',
    UPDATE_SETTINGS_BANK: '/api/institute/tutor/settings/bank',
    UPDATE_SETTINGS_NOTIFICATIONS: '/api/institute/tutor/settings/notifications',
  },
  STUDENT: {
    DASHBOARD: '/api/student/dashboard',
    DASHBOARD_STATS: '/api/student/dashboard/stats',
    COURSE_COMPLETION: '/api/student/dashboard/course-completion',
    STUDY_HOURS: '/api/student/dashboard/study-hours',
    UPCOMING_ACTIVITIES: (limit: number = 10) => `/api/student/dashboard/upcoming-activities?limit=${limit}`,
    FEE_DETAILS: '/api/student/dashboard/fees',
    PAYMENTS_HISTORY: '/api/student/course/payments/history',
    INVOICE: (id: string) => `/api/student/course/payments/${id}/invoice`,
    CLASSES: '/api/student/live-classes',
    LIVE_CLASS: (id: string) => `/api/student/live-classes/${id}`,
    RECORDED_CLASSES: '/api/student/course/my-recorded-video-courses',
    COURSES_ENROLLED: '/api/student/course/my-learning',
    COURSE_PROGRESS: (id: string) => `/api/student/courses/${id}/progress`,
    ASSESSMENTS: '/api/student/exams',
    SUBMIT_EXAM: (id: string) => `/api/student/exams/${id}/submit`,
    CERTIFICATES: '/api/certificates/my-certificates',
    CERTIFICATE_DETAILS: (id: string) => `/api/certificates/my-certificates/${id}`,
    REFERRAL_PROGRAM: '/api/student/referral/program',
    REFERRAL_HISTORY: '/api/student/referral/history',
    COMMUNITIES: '/api/institute/communities',
    COMMUNITY_MESSAGES: (id: string) => `/api/institute/communities/${id}/messages`,
    SETTINGS: '/api/student/settings',
    UPDATE_SETTINGS: '/api/student/settings/profile',
    UPDATE_NOTIFICATIONS: '/api/student/settings/notifications',
    UPDATE_PAYMENT: '/api/student/settings/payment',
    DELETE_ACCOUNT: '/api/student/settings/account',
    ATTENDANCE_ANALYTICS: '/api/student/attendance/analytics',
    COURSE_PERFORMANCE: '/api/student/settings/course-performance',
  },
  PARENT: {
    DASHBOARD: '/api/parent/dashboard',
    ATTENDANCE: '/api/parent/student-attendance',
    NOTIFICATIONS: '/api/parent/notifications',
    NOTIFICATIONS_ALL: (page: number = 1, search: string = '') => `/api/parent/notifications/all?page=${page}&search=${search}`,
    CLEAR_ALL_NOTIFICATIONS: '/api/parent/notifications/clear-all',
    PENDING_EXAMS: '/api/parent/pending-exams',
    EXAM_RESULTS: (page: number = 1) => `/api/parent/assessment/exams?page=${page}`,
    ASSIGNMENT_RESULTS: (page: number = 1) => `/api/parent/assessment/assignments?page=${page}`,
    QUIZ_RESULTS: (page: number = 1) => `/api/parent/assessment/quizzes?page=${page}`,
    PROFILE: '/api/parent/profile',
    UPDATE_PREFERENCES: '/api/parent/profile/preferences',
    UPDATE_PROFILE: '/api/parent/profile',
    FEES: '/api/parent/fees'
  },
  ACCOUNTS_MARKETING: {
    DASHBOARD: '/api/institute/account-marketing/dashboard',
    FEE_TREND: '/api/institute/account-marketing/fee-trend',
    EXPENSE_TREND: '/api/institute/account-marketing/expense-trend',
    RECENT_PAYMENTS: '/api/institute/account-marketing/recent-payments',
    PAYROLL_SUMMARY: '/api/institute/account-marketing/payroll-summary',
    FEES_FILTERS: '/api/institute/account-marketing/fees/filters',
    FEES_PAID: '/api/institute/account-marketing/fees/paid',
    FEES_DUE: '/api/institute/account-marketing/fees/due',
    FEE_DETAILS: (id: string) => `/api/institute/account-marketing/fees/${id}`,
    STUDENT_PAYMENT_HISTORY: (studentId: string) => `/api/institute/account-marketing/fees/student/${studentId}`,
    REMIND_FEE: (installmentId: string) => `/api/institute/account-marketing/fees/remind/${installmentId}`,
    SALARY_FILTERS: '/api/institute/account-marketing/salaries/filters',
    SALARY_PENDING: '/api/institute/account-marketing/salaries/pending',
    SALARY_PAID: '/api/institute/account-marketing/salaries/paid',
    SALARY_APPROVED: '/api/institute/account-marketing/salaries/approved',
    SALARY_DETAILS: (staffId: string) => `/api/institute/account-marketing/salaries/${staffId}`,
    SALARY_CALCULATE: (staffId: string) => `/api/institute/account-marketing/salaries/calculate/${staffId}`,
    SALARY_APPROVE: '/api/institute/account-marketing/salaries/approve',
    SALARY_PAY: '/api/institute/account-marketing/salaries/pay',
    STAFF_ALL: '/api/institute/account-marketing/staff',
    STAFF_ADD: '/api/institute/account-marketing/staff/add',
    DEPARTMENTS: '/api/institute/account-marketing/departments',
    COURSES: '/api/institute/account-marketing/courses',
    STAFF_ATTENDANCE_STATS: (staffId: string) => `/api/institute/account-marketing/salaries/attendance-stats/${staffId}`,
    STAFF_ATTENDANCE_CALENDAR: (staffId: string) => `/api/institute/account-marketing/salaries/attendance-calendar/${staffId}`,
    SETTINGS: '/api/institute/account-marketing/settings',
    SETTINGS_BANK: '/api/institute/account-marketing/settings/bank',
    SETTINGS_PROFILE: '/api/institute/account-marketing/settings/profile',
    SETTINGS_ALERTS: '/api/institute/account-marketing/settings/alerts',
    MARKETING_BROADCAST: '/api/institute/account-marketing/broadcast',
    VERIFY_FACE: '/api/institute/account-marketing/verify-face',
  },
  PAYMENTS: {
    CREATE_ORDER: '/api/payments/create-order',
    VERIFY: '/api/payments/verify',
    INVOICE_DATA: (transactionId: string) => `/api/payments/invoice/${transactionId}`
  },
  PRICING: {
    INSTITUTE: '/api/pricing/institute',
    COURSE_CREATOR: '/api/pricing/course-creator',
  }
};
