import { USER_ROLES, SUBSCRIPTION_PLANS, FEATURES, UserRole, SubscriptionPlan, FeatureKey } from '../types';

export const ROLE_FEATURES: Record<UserRole, FeatureKey[]> = {
  [USER_ROLES.STUDENT]: [
    FEATURES.DOCUMENT_UPLOAD,
    FEATURES.ADVANCED_SEARCH
  ],
  [USER_ROLES.ONLINETUTOR]: [
    FEATURES.DOCUMENT_UPLOAD,
    FEATURES.ADVANCED_SEARCH,
    FEATURES.COLLABORATION,
    FEATURES.ANALYTICS
  ],
  [USER_ROLES.OFFLINETUTOR]: [
    FEATURES.DOCUMENT_UPLOAD,
    FEATURES.ADVANCED_SEARCH,
    FEATURES.COLLABORATION,
    FEATURES.ANALYTICS
  ],
  [USER_ROLES.INSTITUTE]: [
    FEATURES.DOCUMENT_UPLOAD,
    FEATURES.ADVANCED_SEARCH,
    FEATURES.AI_ANALYSIS,
    FEATURES.TEAM_MANAGEMENT,
    FEATURES.ANALYTICS,
    FEATURES.UNLIMITED_STORAGE,
    FEATURES.COLLABORATION
  ],
  [USER_ROLES.ADMIN]: Object.values(FEATURES) as FeatureKey[],
  [USER_ROLES.SUPER_ADMIN]: Object.values(FEATURES) as FeatureKey[],
  [USER_ROLES.ACCOUNTS_MARKETING]: [
    FEATURES.DOCUMENT_UPLOAD,
    FEATURES.ADVANCED_SEARCH,
    FEATURES.ANALYTICS,
    FEATURES.TEAM_MANAGEMENT,
    FEATURES.UNLIMITED_STORAGE,
    FEATURES.API_ACCESS,
    FEATURES.CUSTOM_BRANDING
  ],
  [USER_ROLES.PARENT]: [
    FEATURES.DOCUMENT_UPLOAD,
    FEATURES.ANALYTICS,
    FEATURES.PARENT_DASHBOARD
  ],
  [USER_ROLES.COURSE_CREATOR]: [
    FEATURES.DOCUMENT_UPLOAD,
    FEATURES.ADVANCED_SEARCH,
    FEATURES.COURSE_CREATION,
    FEATURES.ANALYTICS
  ]
};

export const SUBSCRIPTION_FEATURES: Record<SubscriptionPlan, FeatureKey[]> = {
  [SUBSCRIPTION_PLANS.FREE]: [
    FEATURES.DOCUMENT_UPLOAD
  ],
  [SUBSCRIPTION_PLANS.BASIC]: [
    FEATURES.DOCUMENT_UPLOAD,
    FEATURES.ADVANCED_SEARCH,
    FEATURES.AI_ANALYSIS
  ],
  [SUBSCRIPTION_PLANS.PREMIUM]: [
    FEATURES.DOCUMENT_UPLOAD,
    FEATURES.ADVANCED_SEARCH,
    FEATURES.AI_ANALYSIS,
    FEATURES.COLLABORATION,
    FEATURES.API_ACCESS,
    FEATURES.ANALYTICS
  ],
  [SUBSCRIPTION_PLANS.ENTERPRISE]: Object.values(FEATURES) as FeatureKey[]
};

export const ROLE_DISPLAY_NAMES: Record<UserRole, string> = {
  [USER_ROLES.ADMIN]: 'System Administrator',
  [USER_ROLES.SUPER_ADMIN]: 'Super Admin',
  [USER_ROLES.INSTITUTE]: 'Institute Admin',
  [USER_ROLES.ONLINETUTOR]: 'Online Tutor',
  [USER_ROLES.OFFLINETUTOR]: 'Offline Faculty',
  [USER_ROLES.STUDENT]: 'Student',
  [USER_ROLES.PARENT]: 'Parent / Guardian',
  [USER_ROLES.ACCOUNTS_MARKETING]: 'Accounts & Marketing',
  [USER_ROLES.COURSE_CREATOR]: 'Course Creator'
};
